//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexaEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexaEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   You have reached the end of file. Do you want append one byte ? This operation cannot be canceled if you continue.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AppendByteConfirmationString {
            get {
                return ResourceManager.GetString("AppendByteConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bookmarks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BookmarksString {
            get {
                return ResourceManager.GetString("BookmarksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Byte action과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ByteActionString {
            get {
                return ResourceManager.GetString("ByteActionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bytes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BytesTagString {
            get {
                return ResourceManager.GetString("BytesTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Byte과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ByteString {
            get {
                return ResourceManager.GetString("ByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel long process과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CancelLongProcessString {
            get {
                return ResourceManager.GetString("CancelLongProcessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to cancel long process.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CancelLongProcessToolTipString {
            get {
                return ResourceManager.GetString("CancelLongProcessToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear bookmark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ClearBookMarkString {
            get {
                return ResourceManager.GetString("ClearBookMarkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ClearString {
            get {
                return ResourceManager.GetString("ClearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to go to at position.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ClickToGoAtPositionString {
            get {
                return ResourceManager.GetString("ClickToGoAtPositionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloseString {
            get {
                return ResourceManager.GetString("CloseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t convert this string to long과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ConvertStringToLongErrorString {
            get {
                return ResourceManager.GetString("ConvertStringToLongErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy as ASCII과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyAsASCIIString {
            get {
                return ResourceManager.GetString("CopyAsASCIIString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy as decimal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyAsDecimalString {
            get {
                return ResourceManager.GetString("CopyAsDecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy as hexadecimal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyAsHexadecimalString {
            get {
                return ResourceManager.GetString("CopyAsHexadecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TBL string (character file loaded)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyAsTBLString {
            get {
                return ResourceManager.GetString("CopyAsTBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy selection as ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopySelectionAsString {
            get {
                return ResourceManager.GetString("CopySelectionAsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count of과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CountOfString {
            get {
                return ResourceManager.GetString("CountOfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default TBL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DefaultTBLString {
            get {
                return ResourceManager.GetString("DefaultTBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteString {
            get {
                return ResourceManager.GetString("DeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DescriptionString {
            get {
                return ResourceManager.GetString("DescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   00=&lt;NUL&gt;
        ///01=&lt;SOH&gt;
        ///02=&lt;STX&gt;
        ///03=&lt;ETX&gt;
        ///04=&lt;PF&gt;
        ///05=&lt;HT&gt;
        ///06=&lt;LC&gt;
        ///07=&lt;DEL&gt;
        ///08=&lt;GE&gt;
        ///09=&lt;RLF&gt;
        ///0A=&lt;SMM&gt;
        ///0B=&lt;VT&gt;
        ///0C=&lt;FF&gt;
        ///0D=&lt;CR&gt;
        ///0E=&lt;SO&gt;
        ///0F=&lt;SI&gt;
        ///10=&lt;DLE&gt;
        ///11=&lt;DC1&gt;
        ///12=&lt;DC2&gt;
        ///13=&lt;TM&gt;
        ///14=&lt;RES&gt;
        ///15=&lt;NL&gt;
        ///16=&lt;BS&gt;
        ///17=&lt;IL&gt;
        ///18=&lt;CAN&gt;
        ///19=&lt;EM&gt;
        ///1A=&lt;CC&gt;
        ///1B=&lt;CU1&gt;
        ///1C=&lt;IFS&gt;
        ///1D=&lt;IGS&gt;
        ///1E=&lt;IRS&gt;
        ///1F=&lt;IUS&gt;
        ///20=&lt;DS&gt;
        ///21=&lt;SOS&gt;
        ///22=&lt;FS&gt;
        ///23=.
        ///24=&lt;BYP&gt;
        ///25=&lt;LF&gt;
        ///26=&lt;ETB&gt;
        ///27=&lt;ESC&gt;
        ///28=.
        ///29=.
        ///2A=&lt;SM&gt;
        ///2B=&lt;CU2&gt;
        ///2C=.
        ///2D=&lt;ENQ&gt;
        ///2E=&lt;ACK&gt;
        ///2F=&lt;BEL&gt;
        ///30=.
        ///31=.
        ///32=&lt;SYN&gt;
        ///33=.
        ///34=&lt;PN&gt;
        ///35=&lt;RS&gt;
        ///36=&lt;UC&gt;
        ///37=&lt;EOT&gt;
        ///38[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EBCDIC {
            get {
                return ResourceManager.GetString("EBCDIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   00=.
        ///01=.
        ///02=.
        ///03=.
        ///04=.
        ///05=.
        ///06=.
        ///07=.
        ///08=.
        ///09=.
        ///0A=.
        ///0B=.
        ///0C=.
        ///0D=.
        ///0E=.
        ///0F=.
        ///10=.
        ///11=.
        ///12=.
        ///13=.
        ///14=.
        ///15=.
        ///16=.
        ///17=.
        ///18=.
        ///19=.
        ///1A=.
        ///1B=.
        ///1C=.
        ///1D=.
        ///1E=.
        ///1F=.
        ///20=.
        ///21=.
        ///22=.
        ///23=.
        ///24=.
        ///25=.
        ///26=.
        ///27=.
        ///28=.
        ///29=.
        ///2A=.
        ///2B=.
        ///2C=.
        ///2D=.
        ///2E=.
        ///2F=.
        ///30=.
        ///31=.
        ///32=.
        ///33=.
        ///34=.
        ///35=.
        ///36=.
        ///37=.
        ///38=.
        ///39=.
        ///3A=.
        ///3B=.
        ///3C=.
        ///3D=.
        ///3E=.
        ///3F=.
        ///40=.
        ///41=.
        ///42=.
        ///43=.
        ///44=.
        ///45=.
        ///46=.
        ///47=.
        ///48=.
        ///49=.
        ///4A=¢
        ///4B=.
        ///4C=&lt;
        ///4D=(
        ///4E=+
        ///4F=|
        ///50=&amp;
        ///51=.
        ///52=.
        ///53=.
        ///54=.
        ///55[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EBCDICNoSpecialChar {
            get {
                return ResourceManager.GetString("EBCDICNoSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;end&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EndTagString {
            get {
                return ResourceManager.GetString("EndTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter hexadecimal value ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EnterHexValueMsgString {
            get {
                return ResourceManager.GetString("EnterHexValueMsgString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   20= 
        ///21=!
        ///22=&quot;
        ///23=#
        ///24=$
        ///25=%
        ///26=&amp;
        ///27=&apos;
        ///28=(
        ///29=)
        ///2A=*
        ///2B=+
        ///2C=,
        ///2D=-
        ///2E=.
        ///2F=/
        ///30=0
        ///31=1
        ///32=2
        ///33=3
        ///34=4
        ///35=5
        ///36=6
        ///37=7
        ///38=8
        ///39=9
        ///3A=:
        ///3B=;
        ///3C=&lt;
        ///3D==
        ///3E=&gt;
        ///3F=?
        ///40=@
        ///41=A
        ///42=B
        ///43=C
        ///44=D
        ///45=E
        ///46=F
        ///47=G
        ///48=H
        ///49=I
        ///4A=J
        ///4B=K
        ///4C=L
        ///4D=M
        ///4E=N
        ///4F=O
        ///50=P
        ///51=Q
        ///52=R
        ///53=S
        ///54=T
        ///55=U
        ///56=V
        ///57=W
        ///58=X
        ///59=Y
        ///5A=Z
        ///5B=[
        ///5C=\
        ///5D=]
        ///5E=^
        ///5F=_
        ///60=`
        ///61=a
        ///62=b
        ///63=c
        ///64=d
        ///65=e
        ///66=f
        ///67=g
        ///68=h
        ///69=i
        ///6A=j
        ///6B=k
        ///6C=l
        ///6D=m
        ///6E=n
        ///6F=o
        ///70=p
        ///71=q
        ///72=r
        ///73=s
        ///74=t
        ///75[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EUCKR {
            get {
                return ResourceManager.GetString("EUCKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want close the current file and open : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FileDroppingConfirmationString {
            get {
                return ResourceManager.GetString("FileDroppingConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill selection with byte과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FillSelectionAloneString {
            get {
                return ResourceManager.GetString("FillSelectionAloneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill selection with byte...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FillSelectionString {
            get {
                return ResourceManager.GetString("FillSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FindAllString {
            get {
                return ResourceManager.GetString("FindAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find and Replace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FindAndReplaceString {
            get {
                return ResourceManager.GetString("FindAndReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Byte to search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FindByteString {
            get {
                return ResourceManager.GetString("FindByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find First과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FindFirstString {
            get {
                return ResourceManager.GetString("FindFirstString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Last과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FindLastString {
            get {
                return ResourceManager.GetString("FindLastString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Next과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FindNextString {
            get {
                return ResourceManager.GetString("FindNextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find all occurence of selection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FindSelectionString {
            get {
                return ResourceManager.GetString("FindSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FindString {
            get {
                return ResourceManager.GetString("FindString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find what:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FindWhatString {
            get {
                return ResourceManager.GetString("FindWhatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First byte과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FirstByteString {
            get {
                return ResourceManager.GetString("FirstByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hex과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HexString {
            get {
                return ResourceManager.GetString("HexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Highlight all data find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HighLightSettingString {
            get {
                return ResourceManager.GetString("HighLightSettingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kb과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KBTagString {
            get {
                return ResourceManager.GetString("KBTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Length과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LengthString {
            get {
                return ResourceManager.GetString("LengthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ln과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LineStatusBarTagString {
            get {
                return ResourceManager.GetString("LineStatusBarTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;ln&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LineTagString {
            get {
                return ResourceManager.GetString("LineTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Long과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LongString {
            get {
                return ResourceManager.GetString("LongString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mb과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MBTagString {
            get {
                return ResourceManager.GetString("MBTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ok과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OkString {
            get {
                return ResourceManager.GetString("OkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is locked. Do you want to open it in read-only mode?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OpenAsReadOnlyString {
            get {
                return ResourceManager.GetString("OpenAsReadOnlyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste operation reached the end of file. Do you want extend the file for complete operation ? This operation cannot be canceled if you continue.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PasteExtendByteConfirmationString {
            get {
                return ResourceManager.GetString("PasteExtendByteConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste from clipboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PasteFromClipboardString {
            get {
                return ResourceManager.GetString("PasteFromClipboardString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste without inserting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PasteNotInsertString {
            get {
                return ResourceManager.GetString("PasteNotInsertString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PositionString {
            get {
                return ResourceManager.GetString("PositionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReplaceAllString {
            get {
                return ResourceManager.GetString("ReplaceAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace by byte과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReplaceByByteString {
            get {
                return ResourceManager.GetString("ReplaceByByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace Next과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReplaceNextString {
            get {
                return ResourceManager.GetString("ReplaceNextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace byte in selection...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReplaceSelectionString {
            get {
                return ResourceManager.GetString("ReplaceSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReplaceString {
            get {
                return ResourceManager.GetString("ReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim the data on the find length when replace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReplaceTrimSettingString {
            get {
                return ResourceManager.GetString("ReplaceTrimSettingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace with byte과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReplaceWithByteString {
            get {
                return ResourceManager.GetString("ReplaceWithByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace with:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ReplaceWithString {
            get {
                return ResourceManager.GetString("ReplaceWithString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select all과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SelectAllString {
            get {
                return ResourceManager.GetString("SelectAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set bookmark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SetBookMarkString {
            get {
                return ResourceManager.GetString("SetBookMarkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TBL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TBLString {
            get {
                return ResourceManager.GetString("TBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This string are not hex과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ThisStringAreNotHexString {
            get {
                return ResourceManager.GetString("ThisStringAreNotHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UndoString {
            get {
                return ResourceManager.GetString("UndoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   00=.
        ///01=.
        ///0A=.
        ///0D=.
        ///20= 
        ///22=&quot;
        ///23=.
        ///28=.
        ///29=.
        ///2C=.
        ///2F=/
        ///30=.
        ///31=1
        ///32=2
        ///33=3
        ///34=4
        ///35=5
        ///36=6
        ///37=7
        ///38=8
        ///39=9
        ///3A=.
        ///3B=.
        ///3C=&lt;
        ///3D==
        ///3E=&gt;
        ///3F=.
        ///40=.
        ///41=A
        ///42=B
        ///43=C
        ///44=D
        ///45=E
        ///46=F
        ///47=G
        ///48=H
        ///49=I
        ///4A=J
        ///4B=K
        ///4C=L
        ///4D=M
        ///4E=N
        ///4F=O
        ///50=P
        ///51=Q
        ///52=R
        ///53=S
        ///54=T
        ///55=U
        ///56=V
        ///57=W
        ///58=X
        ///59=Y
        ///5A=Z
        ///5B=$
        ///5C=\
        ///5D=)
        ///5E=;
        ///5F=�?
        ///60=-
        ///61=a
        ///62=b
        ///63=c
        ///64=d
        ///65=e
        ///66=f
        ///67=g
        ///68=h
        ///69=i
        ///6A=j
        ///6B=k
        ///6C=l
        ///6D=m
        ///6E=n
        ///6F=o
        ///70=p
        ///71=q
        ///72=r
        ///73=s
        ///74=t
        ///75=u
        ///76=v
        ///77=w
        ///78=x
        ///79=y
        ///7[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UTF8 {
            get {
                return ResourceManager.GetString("UTF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValueString {
            get {
                return ResourceManager.GetString("ValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error is occurs when writing.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WritingErrorExeptionString {
            get {
                return ResourceManager.GetString("WritingErrorExeptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset zoom to 100%과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZoomResetString {
            get {
                return ResourceManager.GetString("ZoomResetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZoomString {
            get {
                return ResourceManager.GetString("ZoomString", resourceCulture);
            }
        }
    }
}
